for i in range(5):
  if i ==3:
    raise Exception("exception message as 3 is found")
  else:
    print(i)